{ config, pkgs, hyprland-config, ... }:
let
  qs = config.services.quickshell-ricelin.package;
  # wf-recorder 0.6.0 doesn't build against ffmpeg's default (9.0): it reads
  # AVCodec.sample_fmts, a field removed upstream. Pin ffmpeg_6 until
  # wf-recorder is patched for the new API.
  wf-recorder = pkgs.wf-recorder.override { ffmpeg = pkgs.ffmpeg_6; };
  screenshot-area = pkgs.writeShellScript "screenshot-area" ''
    grim -g "$(slurp)" - | wl-copy
  '';
  screenshot-full = pkgs.writeShellScript "screenshot-full" ''
    grim - | wl-copy
  '';
  record-area = pkgs.writeShellScript "record-area" ''
    mkdir -p "$HOME/Videos"
    exec ${wf-recorder}/bin/wf-recorder -g "$(slurp)" \
      -f "$HOME/Videos/$(date +%Y-%m-%d-%H%M%S).mp4"
  '';
  # wf-recorder prompts interactively when several outputs exist, which hangs
  # when launched from a menu, so pick the focused one explicitly.
  record-full = pkgs.writeShellScript "record-full" ''
    mkdir -p "$HOME/Videos"
    output=$(hyprctl -j activeworkspace | ${pkgs.jq}/bin/jq -r .monitor)
    exec ${wf-recorder}/bin/wf-recorder -o "$output" \
      -f "$HOME/Videos/$(date +%Y-%m-%d-%H%M%S).mp4"
  '';
  record-stop = pkgs.writeShellScript "record-stop" ''
    pkill -INT -x wf-recorder
  '';
  new-browser-window = pkgs.writeShellScript "new-browser-window" ''
    desktop=$(${pkgs.xdg-utils}/bin/xdg-settings get default-web-browser)
    desktop_file=$(find /run/current-system/sw/share/applications $HOME/.local/share/applications $HOME/.nix-profile/share/applications /usr/share/applications -name "$desktop" 2>/dev/null | head -1)
    binary=$(${pkgs.gnugrep}/bin/grep -m1 '^Exec=' "$desktop_file" | ${pkgs.gnused}/bin/sed 's/^Exec=//;s/ %.//g')
    exec ''${binary:-xdg-open} --new-window
  '';
in
{
  home.packages = with pkgs; [
    hyprpaper
    hypridle
    hyprpolkitagent
    hyprmoncfg
    grim
    slurp
    wl-clipboard
    cliphist
    brightnessctl
    playerctl
    pavucontrol
  ] ++ [ wf-recorder ];

  # Registers hyprland.portal in the profile's portal dir and points the frontend
  # at it, so ScreenCast (screen recording and sharing) has a backend.
  xdg.portal = {
    enable = true;
    extraPortals = [
      config.wayland.windowManager.hyprland.finalPortalPackage
      pkgs.xdg-desktop-portal-gtk
    ];
    config.common = {
      default = [ "hyprland" "gtk" ];
      "org.freedesktop.impl.portal.ScreenCast" = [ "hyprland" ];
      "org.freedesktop.impl.portal.Screenshot" = [ "hyprland" ];
    };
  };

  wayland.windowManager.hyprland = {
    enable = true;
    configType = "lua";
    settings = {
      mod          = { _var = "SUPER"; };
      terminal     = { _var = "ghostty"; };
      lock         = { _var = "hyprlock"; };
      claude_here  = { _var = "${hyprland-config}/scripts/claude-here.sh"; };
      browser      = { _var = "${new-browser-window}"; };
      monitor  = [
        { output = "eDP-1"; mode = "preferred"; position = "auto"; scale = 2; }
        { output = "";      mode = "preferred"; position = "auto"; scale = 1; }
      ];
    };
    extraConfig = builtins.readFile "${hyprland-config}/hypr/hyprland.lua" + ''

      hl.on("hyprland.start", function()
        hl.exec_cmd("sh -c 'QML2_IMPORT_PATH=${pkgs.qt6Packages.qt5compat}/lib/qt-6/qml ${qs}/bin/quickshell -c hyprsphere'")
      end)
    '';
  };

  xdg.configFile."hypr/hyprland.conf" = { text = "# See hyprland.lua"; force = true; };
  xdg.configFile."hypr/hyprpaper.conf".source = "${hyprland-config}/hypr/hyprpaper.conf";
  xdg.configFile."hypr/hyprlock.conf".source  = "${hyprland-config}/hypr/hyprlock.conf";
  xdg.configFile."hypr/hypridle.conf".source  = "${hyprland-config}/hypr/hypridle.conf";
  xdg.configFile."hypr/scripts" = {
    source = "${hyprland-config}/scripts";
    recursive = true;
  };

  # hyprland.lua does `require("monitors")`, expecting hyprmoncfgd to have
  # written ~/.config/hypr/monitors.lua. Seed a stub with hyprmoncfg's own
  # "generated" header on first activation only, so the daemon's real writes
  # afterward are never clobbered by a home-manager switch.
  home.activation.seedHyprMonitorsLua = config.lib.dag.entryAfter [ "writeBoundary" ] ''
    monitorsLua="$HOME/.config/hypr/monitors.lua"
    if [ ! -e "$monitorsLua" ]; then
      $DRY_RUN_CMD install -Dm644 ${pkgs.writeText "monitors.lua" "-- Generated by hyprmoncfg\n"} "$monitorsLua"
    fi
  '';

  systemd.user.services.hyprmoncfgd = {
    Unit = {
      Description = "Hyprland monitor profile daemon (hyprmoncfgd)";
      After = [ "hyprland-session.target" ];
      PartOf = [ "hyprland-session.target" ];
    };
    Service = {
      Type = "simple";
      ExecStart = "${pkgs.hyprmoncfg}/bin/hyprmoncfgd";
      Restart = "on-failure";
      RestartSec = 2;
    };
    Install = {
      WantedBy = [ "hyprland-session.target" ];
    };
  };

  xdg.desktopEntries = {
    shutdown = {
      name = "Shutdown";
      exec = "systemctl poweroff";
      icon = "system-shutdown";
      categories = [ "System" ];
    };
    reboot = {
      name = "Reboot";
      exec = "systemctl reboot";
      icon = "system-reboot";
      categories = [ "System" ];
    };
    suspend = {
      name = "Suspend";
      exec = "systemctl suspend";
      icon = "system-suspend";
      categories = [ "System" ];
    };
    lock = {
      name = "Lock Screen";
      exec = "hyprlock";
      icon = "system-lock-screen";
      categories = [ "System" ];
    };
    logout = {
      name = "Logout";
      exec = "hyprctl dispatch exit";
      icon = "system-log-out";
      categories = [ "System" ];
    };
    restart-wifi = {
      name = "Restart WiFi";
      exec = "systemctl restart NetworkManager";
      icon = "network-wireless";
      categories = [ "System" ];
    };
    toggle-bluetooth = {
      name = "Toggle Bluetooth";
      exec = "rfkill toggle bluetooth";
      icon = "bluetooth";
      categories = [ "System" ];
    };
    screenshot-area = {
      name = "Screenshot (Area)";
      exec = "${screenshot-area}";
      icon = "accessories-screenshot";
      categories = [ "Utility" ];
    };
    screenshot-full = {
      name = "Screenshot (Full)";
      exec = "${screenshot-full}";
      icon = "accessories-screenshot";
      categories = [ "Utility" ];
    };
    record-area = {
      name = "Record (Area)";
      exec = "${record-area}";
      icon = "media-record";
      categories = [ "Utility" ];
    };
    record-full = {
      name = "Record (Full)";
      exec = "${record-full}";
      icon = "media-record";
      categories = [ "Utility" ];
    };
    record-stop = {
      name = "Record (Stop)";
      exec = "${record-stop}";
      icon = "media-playback-stop";
      categories = [ "Utility" ];
    };
  };
}
